### ISSUE TITLE
`getting-started/kubernetes-quickstart` page is outdated.

### ISSUE THREAD

**Issue by khoramism** [pinot-contrib/pinot-docs#359]
Here there is a part that we setup a kafka cluster using helm and bitnami's packages, Bitnami's helm packages do deploy kafka in a KRaft Mode by default, even though throughout the documentation on apache pinot we are setting up the zookeeper quorum version , I manged to get it working using these values for the helm package, even though we need to provide a fix for this problem, either set it up using KRaft or change documentation to work with zookeeper values.

my values.yaml file:
```yaml
controller:
  replicaCount: 0

broker:
  replicaCount: 3

kraft:
  enabled: false

zookeeper:
  enabled: true
  replicaCount: 3

listeners:
  client:
    protocol: PLAINTEXT
```
